#!/bin/bash
set -e
# immudb-setup-operator.sh — immudb Operator Database Setup
# Starts immudb, logs in as superadmin, creates the operator
# database and user, tests the connection, and writes the
# credentials to ~/.identity/db_secrets.env.
#
# Run ONCE after immudb_setup.sh. Idempotent — re-running will
# skip creation if the database and user already exist.

BIN_DIR="${BIN_DIR:-$HOME/bin}"
IMMUD_BIN="$BIN_DIR/immudb"
IMMUADMIN="$BIN_DIR/immuadmin"
IMMUCLIENT="$BIN_DIR/immuclient"

DATA_DIR="${DATA_DIR:-$HOME/.orp_vault/data}"
LOG_FILE="$HOME/.orp_vault/immudb.log"

mkdir -p "$DATA_DIR" "$(dirname "$LOG_FILE")"

echo "[*] Verifying immudb binaries..."
for cmd in "$IMMUD_BIN" "$IMMUADMIN" "$IMMUCLIENT"; do
    if [ ! -x "$cmd" ]; then
        echo "ERROR: Binary not found: $cmd"
        echo "Run immudb_setup.sh first."
        exit 1
    fi
    echo "Found: $cmd"
done

echo "[*] Starting immudb server if not running..."
if pgrep -x immudb >/dev/null 2>&1; then
    echo "immudb is already running."
else
    nohup "$IMMUD_BIN" \
        --dir "$DATA_DIR" \
        --address 127.0.0.1 \
        --port 3322 \
        --auth=true \
        --maintenance=false \
        >> "$LOG_FILE" 2>&1 &
    echo "Waiting for immudb to accept connections..."
    TRIES=0
    while ! "$IMMUCLIENT" status >/dev/null 2>&1; do
        sleep 0.5
        TRIES=$((TRIES + 1))
        [ $TRIES -ge 30 ] && {
            echo "ERROR: immudb did not start after 15s. Check: $LOG_FILE"
            exit 1
        }
    done
    echo "immudb is ready."
fi

echo "[*] Logging in as superadmin..."
if ! "$IMMUADMIN" login immudb; then
    echo "ERROR: Superadmin login failed."
    exit 1
fi
echo "Superadmin login successful."

echo "[*] Database creation..."
read -r -p "Enter new database name [brgy_bunaodb]: " IMMUDBDB
IMMUDBDB="${IMMUDBDB:-brgy_bunaodb}"

if "$IMMUADMIN" database list 2>/dev/null | awk '{print $1}' | grep -qw "^${IMMUDBDB}$"; then
    echo "Database '${IMMUDBDB}' already exists — skipping creation."
else
    "$IMMUADMIN" database create "$IMMUDBDB"
    echo "Database '${IMMUDBDB}' created."
fi

echo "[*] Operator user creation..."
read -r -p "Enter operator username [orp_operator]: " IMMUDBUSER
IMMUDBUSER="${IMMUDBUSER:-orp_operator}"

if "$IMMUADMIN" user list 2>/dev/null | awk '{print $1}' | grep -qw "^${IMMUDBUSER}$"; then
    echo "User '${IMMUDBUSER}' already exists — skipping creation."
    echo "To reset the password: ~/bin/immuadmin user changepassword ${IMMUDBUSER}"
else
    "$IMMUADMIN" user create "$IMMUDBUSER" readwrite "$IMMUDBDB"
    echo "User '${IMMUDBUSER}' created with readwrite access."
fi

echo "[*] Testing operator login..."
if "$IMMUCLIENT" login "$IMMUDBUSER" --database "$IMMUDBDB"; then
    "$IMMUCLIENT" set __orp_healthcheck__ "ok" >/dev/null 2>&1 || true
    "$IMMUCLIENT" get __orp_healthcheck__ >/dev/null 2>&1 || true
    echo "Read/write test passed."
else
    echo "Login verification failed — check the password you entered."
fi

echo "[*] Writing credentials file..."
SECRETS_FILE="$HOME/.identity/db_secrets.env"
mkdir -p "$HOME/.identity"
chmod 700 "$HOME/.identity"

cat > "$SECRETS_FILE" <<EOF
# db_secrets.env — ORP immudb Operator Credentials
# Generated by immudb-setup-operator.sh on $(date)
# SECURITY NOTES:
#   - chmod 600 (owner read/write only).
#   - Do NOT commit this file to git.
#   - Operator PASSWORD is not stored here.

IMMUDB_USER="$IMMUDBUSER"
IMMUDB_DB="$IMMUDBDB"
EOF

chmod 600 "$SECRETS_FILE"
echo "Credentials written to: $SECRETS_FILE"

echo "[*] Setup complete."
echo "Database: $IMMUDBDB"
echo "Username: $IMMUDBUSER"
echo "Secrets:  $SECRETS_FILE"
localhost:~/openrespublica-ph.github.io# cat immudb_setup.sh
#!/bin/bash
set -e
# Build immudb binaries inside Alpine (proot-distro) and check versions

echo "[*] Updating Alpine packages..."
apk update && apk upgrade

echo "[*] Installing build dependencies..."
apk add --no-cache git make clang cmake go libc-dev bash

echo "[*] Verifying toolchain versions..."
git --version
make --version
clang --version
go version

mkdir -p "$HOME/bin"

# Clone immudb if not already present
if [ ! -d "$HOME/immudb" ]; then
  echo "[*] Cloning immudb source..."
  git clone --depth=1 --branch v1.10.0 https://github.com/codenotary/immudb.git "$HOME/immudb"
fi

cd "$HOME/immudb"

# Build binaries only if missing
if [ ! -f "$HOME/bin/immudb" ] || [ ! -f "$HOME/bin/immuclient" ] || [ ! -f "$HOME/bin/immuadmin" ]; then
  echo "[*] Building immudb binaries..."
  make immudb immuclient immuadmin
  cp immudb immuclient immuadmin "$HOME/bin/"
else
  echo "[*] Binaries already present, skipping rebuild."
fi

echo "[*] Checking immudb binary versions..."
"$HOME/bin/immudb" version || true
"$HOME/bin/immuclient" version || true
"$HOME/bin/immuadmin" version || true

echo "[*] Build and version check complete."
